[package]
name = "polymesh-dart-common"
version = "0.1.0"
edition = "2024"
description = "Polymesh DART assets."
authors = ["Polymesh Labs"]
license = "GPL-3.0"

[dependencies]

[features]
default = [ "std" ]

std = [ ]
