//! Client signature scheme `DS`.
//!
//! Batch Schnorr, Fig. 2 of <https://iacr.org/archive/asiacrypt2004/33290273/33290273.pdf>.
//! A payment's `l` ephemeral keys were all generated by one client, so one prover knows every `sk`
//! and one `(t, s)` covers the whole payment instead of `l` of them. Refund signs with the single
//! key `sk_ref`, which is the same construction over one key.

use crate::error::Error;
use ark_ec::{AffineRepr, CurveGroup, VariableBaseMSM, scalar_mul::BatchMulPreprocessing};
use ark_ff::PrimeField;
use ark_serialize::{CanonicalDeserialize, CanonicalSerialize};
use ark_std::{UniformRand, vec::Vec};
use dock_crypto_utils::randomized_mult_checker::RandomizedMultChecker;
use rand_core::CryptoRngCore;
use schnorr_pok::compute_random_oracle_challenge;
use sha2::Sha256;
use zeroize::{Zeroize, ZeroizeOnDrop};

pub const SIGNATURE_DST: &[u8] = b"POLYMESH-BAT-V01-SIGNATURE";

#[derive(Clone, CanonicalSerialize, CanonicalDeserialize, Zeroize, ZeroizeOnDrop)]
pub struct Keypair<G: AffineRepr> {
    pub sk: G::ScalarField,
    #[zeroize(skip)]
    pub pk: G,
}

impl<G: AffineRepr> Keypair<G> {
    pub fn new<R: CryptoRngCore>(rng: &mut R, sig_base: &G) -> Self {
        let sk = G::ScalarField::rand(rng);
        let pk = sig_base.mul_bigint(sk.into_bigint()).into_affine();
        Self { sk, pk }
    }

    /// One windowed table over the shared `sig_base`, reused for all `num_keys` public keys. A client
    /// generates one ephemeral key per token, so this is the issuance-side form.
    pub fn new_batch<R: CryptoRngCore>(rng: &mut R, sig_base: &G, num_keys: usize) -> Vec<Self> {
        let mut sk = (0..num_keys)
            .map(|_| G::ScalarField::rand(rng))
            .collect::<Vec<_>>();
        let table = BatchMulPreprocessing::new(sig_base.into_group(), num_keys.max(1));
        let keypairs = table
            .batch_mul(&sk)
            .into_iter()
            .zip(&sk)
            .map(|(pk, sk)| Self { sk: *sk, pk })
            .collect();
        sk.zeroize();
        keypairs
    }
}

/// One `(t, s)` proving knowledge of the discrete log of every key in an ordered set.
#[derive(Clone, Debug, PartialEq, Eq, CanonicalSerialize, CanonicalDeserialize)]
pub struct BatchSig<G: AffineRepr> {
    pub t: G,
    pub s: G::ScalarField,
}

impl<G: AffineRepr> BatchSig<G> {
    /// `t = sig_base*r`, `s = r + \sum_i{c^i . sk_i}`. One scalar mult regardless of how many keys.
    pub fn new<R: CryptoRngCore>(
        rng: &mut R,
        keypairs: &[Keypair<G>],
        msg: &[u8],
        sig_base: &G,
    ) -> Result<Self, Error> {
        if keypairs.is_empty() {
            return Err(Error::Empty);
        }
        let mut r = G::ScalarField::rand(rng);
        let t = sig_base.mul_bigint(r.into_bigint()).into_affine();
        let pks = keypairs.iter().map(|kp| kp.pk).collect::<Vec<_>>();
        let c = Self::challenge(&t, &pks, msg);
        let mut s = r;
        let mut c_i = c;
        for kp in keypairs {
            s += c_i * kp.sk;
            c_i *= c;
        }
        r.zeroize();
        Ok(Self { t, s })
    }

    /// `sig_base*s == t + \sum_i{pk_i*c^i}`, one MSM of size `n + 1`. Does not reject a repeated key: an
    /// honest prover can open `c^i + c^j` on one `sk`, so distinctness stays the caller's check.
    pub fn verify(
        &self,
        pks: &[G],
        msg: &[u8],
        sig_base: &G,
        rmc: Option<&mut RandomizedMultChecker<G>>,
    ) -> Result<(), Error> {
        if pks.is_empty() {
            return Err(Error::Empty);
        }
        let c = Self::challenge(&self.t, pks, msg);
        let mut bases = Vec::with_capacity(pks.len() + 1);
        let mut scalars = Vec::with_capacity(pks.len() + 1);
        bases.push(*sig_base);
        scalars.push(self.s);
        let mut c_i = c;
        for pk in pks {
            bases.push(*pk);
            scalars.push(-c_i);
            c_i *= c;
        }
        match rmc {
            Some(rmc) => {
                rmc.add_many(bases, &scalars, self.t);
                Ok(())
            }
            None => {
                if G::Group::msm_unchecked(&bases, &scalars) == self.t.into_group() {
                    Ok(())
                } else {
                    Err(Error::InvalidSignature)
                }
            }
        }
    }

    /// Binds the DST, `t`, the ordered public keys and the message. Order matters: the verifier pairs
    /// the `i`-th key with `c^i`, so a reordered or truncated set yields a different challenge.
    fn challenge(t: &G, pks: &[G], msg: &[u8]) -> G::ScalarField {
        let mut bytes = Vec::with_capacity(
            SIGNATURE_DST.len() + 8 + (1 + pks.len()) * t.compressed_size() + msg.len(),
        );
        bytes.extend_from_slice(SIGNATURE_DST);
        t.serialize_compressed(&mut bytes).unwrap();
        bytes.extend_from_slice(&(pks.len() as u64).to_le_bytes());
        for pk in pks {
            pk.serialize_compressed(&mut bytes).unwrap();
        }
        bytes.extend_from_slice(msg);
        compute_random_oracle_challenge::<G::ScalarField, Sha256>(&bytes)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::error::Error;
    use ark_std::rand::{SeedableRng, rngs::StdRng};
    use dock_crypto_utils::randomized_mult_checker::RandomizedMultCheckerGuard;

    type G = ark_pallas::Affine;

    #[test]
    fn batch_sig() {
        // Signs over 1 and 5 keys, then checks every change to the message, base or key set fails.
        let mut rng = StdRng::seed_from_u64(0);
        let sig_base = G::generator();
        let msg = b"message";
        let other = Keypair::new(&mut rng, &sig_base).pk;

        for n in [1, 2, 5] {
            let keypairs = Keypair::new_batch(&mut rng, &sig_base, n);
            let pks = keypairs.iter().map(|kp| kp.pk).collect::<Vec<_>>();
            let sig = BatchSig::new(&mut rng, &keypairs, msg, &sig_base).unwrap();
            sig.verify(&pks, msg, &sig_base, None).unwrap();

            assert_eq!(
                sig.verify(&pks, b"other message", &sig_base, None),
                Err(Error::InvalidSignature)
            );
            let other_sig_base =
                (sig_base * <G as AffineRepr>::ScalarField::from(2u64)).into_affine();
            assert_eq!(
                sig.verify(&pks, msg, &other_sig_base, None),
                Err(Error::InvalidSignature)
            );

            let mut swapped = pks.clone();
            swapped[n - 1] = other;
            assert_eq!(
                sig.verify(&swapped, msg, &sig_base, None),
                Err(Error::InvalidSignature)
            );

            let mut extended = pks.clone();
            extended.push(other);
            assert_eq!(
                sig.verify(&extended, msg, &sig_base, None),
                Err(Error::InvalidSignature)
            );

            if n > 1 {
                let mut reordered = pks.clone();
                reordered.swap(0, n - 1);
                assert_eq!(
                    sig.verify(&reordered, msg, &sig_base, None),
                    Err(Error::InvalidSignature)
                );
                assert_eq!(
                    sig.verify(&pks[..n - 1], msg, &sig_base, None),
                    Err(Error::InvalidSignature)
                );
            }
        }
    }

    #[test]
    fn batch_sig_with_randomized_checker() {
        // Several signatures verifier in one checker.
        let mut rng = StdRng::seed_from_u64(1);
        let sig_base = G::generator();

        let sigs = [1, 3, 5, 8]
            .into_iter()
            .enumerate()
            .map(|(i, n)| {
                let keypairs = Keypair::new_batch(&mut rng, &sig_base, n);
                let pks = keypairs.iter().map(|kp| kp.pk).collect::<Vec<_>>();
                let msg = vec![i as u8; 4];
                let sig = BatchSig::new(&mut rng, &keypairs, &msg, &sig_base).unwrap();
                (sig, pks, msg)
            })
            .collect::<Vec<_>>();

        let verify_all = |rng: &mut StdRng, sigs: &[(BatchSig<G>, Vec<G>, Vec<u8>)]| {
            RandomizedMultCheckerGuard::new_using_rng(rng).with_err(
                Error::InvalidSignature,
                |rmc| {
                    for (sig, pks, msg) in sigs {
                        sig.verify(pks, msg, &sig_base, Some(&mut *rmc))?;
                    }
                    Ok(())
                },
            )
        };

        for (sig, pks, msg) in &sigs {
            sig.verify(pks, msg, &sig_base, None).unwrap();
        }
        verify_all(&mut rng, &sigs).unwrap();

        let mut bad = sigs.clone();
        bad[2].2 = b"other".to_vec();
        for (i, (sig, pks, msg)) in bad.iter().enumerate() {
            assert_eq!(sig.verify(pks, msg, &sig_base, None).is_ok(), i != 2);
        }
        assert_eq!(verify_all(&mut rng, &bad), Err(Error::InvalidSignature));
    }
}
